# Generated by Django 3.0.7 on 2021-06-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210526_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='NecessaryProducts',
            fields=[
                ('nc_prd_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=40)),
                ('nc_products', models.CharField(max_length=40)),
            ],
        ),
    ]
