# Generated by Django 3.0.7 on 2021-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210526_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=30)),
                ('is_logged_in', models.BooleanField()),
            ],
        ),
    ]
