# Generated by Django 3.0.7 on 2021-06-08 00:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_necessaryproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='necessaryproducts',
            name='nc_products',
            field=jsonfield.fields.JSONField(default=dict, max_length=40),
        ),
    ]
