# Generated by Django 3.2.3 on 2021-06-05 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_currentuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentUser',
        ),
    ]
